### ISSUE TITLE
I ran `composer install --ignore-platform-reqs` because of some problem in composer install, and getting these errors

### ISSUE THREAD

**Issue by ArshCypherZ** [hitrov/oci-arm-host-capacity#90]
Error1
PHP Fatal error:  Uncaught Error: Undefined constant "Hitrov\CURLOPT_URL" in /root/oci-arm-host-capacity/src/OciApi.php:243
Stack trace:
#0 /root/oci-arm-host-capacity/src/OciApi.php(132): Hitrov\OciApi->call()
#1 /root/oci-arm-host-capacity/index.php(74): Hitrov\OciApi->getInstances()
#2 {main}
  thrown in /root/oci-arm-host-capacity/src/OciApi.php on line 243

Error 2
composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-curl * but it is missing from your system. Install or enable PHP's curl extension.
  Problem 2
    - phar-io/manifest is locked to version 2.0.3 and an update of this package was not requested.
    - phar-io/manifest 2.0.3 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 3
    - phpunit/php-code-coverage is locked to version 9.2.17 and an update of this package was not requested.
    - phpunit/php-code-coverage 9.2.17 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 4
    - phpunit/phpunit is locked to version 9.5.25 and an update of this package was not requested.
    - phpunit/phpunit 9.5.25 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 5
    - theseer/tokenizer is locked to version 1.2.1 and an update of this package was not requested.
    - theseer/tokenizer 1.2.1 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-intl.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-curl --ignore-platform-req=ext-dom` to temporarily ignore these required extensions.

**Comment by ArshCypherZ** [comment]
Fixed :)

**Comment by exact** [comment]
> Fixed :)

howww

**Comment by mrshmllow** [comment]
> Fixed :)

..................................

**Comment by 111100001** [comment]
this issue still persists for me even after installing php-curl

**Comment by ArshCypherZ** [comment]
> this issue still persists for me even after installing php-curl

you need to ensure that php-curl and composer version is same.
